name: CI

on:
  push:
    branches: 
      - main
      - feature/**
permissions:
      id-token: write
      contents: read
      
jobs:
  frontend-react:
    name: frontend-react
    uses: fernandorquind/pipeline-template/.github/workflows/main_frontend.yml@main-loi
